package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO,
    LLAVE_IZQUIERDA, LLAVE_DERECHA,CORCHETE_IZQUIERDO, CORCHETE_DERECHO, DESCONOCIDO, CARACTER
}